server:
  port: 9411
spring:
  application:
    name: cloud-zipkin
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://root:644886@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    appname: cloud-zipkin
management:
  metrics:
    web:
      server:
        auto-time-requests: false
