
server:
  port: 8900
eureka:
  client:
    service-url:
      defaultZone: http://root:644886@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    appname: cloud-board
turbine:
  aggregator:
    clusterConfig: default
  appConfig: cloud-client
  clusterNameExpression: "'default'"
  #instanceUrlSuffix: /hystrix.stream
spring:
  application:
    name: cloud-board
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'