server:
  port: 8800
spring:
  security:
    basic:
      enabled: true
    user:
      name: root
      password: 644886
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          # uri: https://git.coding.net/yirenyishi/springcloud-config-profile
          uri: https://github.com/pierwzw/springcloud-config.git
          searchPaths: '{application}'
eureka:
  client:
    service-url:
      defaultZone: http://root:644886@localhost:8761/eureka/
    #register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    appname: cloud-config-server
